name: Search Load Test
on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:        # Allows manual run

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Run Load Test
      uses: grafana/k6-action@v0.3.0
      with:
        filename: search-test.js
